version: '3.5'
services:
  openwrt-packages-build-clash:
    image: "openwrtorg/sdk:x86_64-19.07.7"
    container_name: openwrt-packages-build-clash
    volumes:
     - ./bin:/home/build/openwrt/bin
     - .:/home/build/openwrt/package/openwrt-clash
     - ./build.sh:/home/build/openwrt/build.sh
     - ./logs:/home/build/openwrt/logs
    command: "./build.sh"